//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyect_P3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULOSFOTO
    {
        public int IDCliente { get; set; }
        public int IDArticulo { get; set; }
        public int SecPhoto { get; set; }
        public byte[] FOTO { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual VEHICULO VEHICULO { get; set; }
    }
}
