//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyect_P3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOTORE
    {
        public MOTORE()
        {
            this.VEHICULOS = new HashSet<VEHICULO>();
        }
    
        public int IdMotor { get; set; }
        public string Descripcion { get; set; }
        public string Combustible { get; set; }
        public string Transmisión { get; set; }
    
        public virtual ICollection<VEHICULO> VEHICULOS { get; set; }
    }
}
