//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyect_P3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipio
    {
        public Municipio()
        {
            this.VEHICULOS = new HashSet<VEHICULO>();
        }
    
        public int CodigoMunicipio { get; set; }
        public string NombreMunicipio { get; set; }
        public int CodigoProvincia { get; set; }
    
        public virtual Provincia Provincia { get; set; }
        public virtual ICollection<VEHICULO> VEHICULOS { get; set; }
    }
}
