//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyect_P3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provincia
    {
        public Provincia()
        {
            this.Municipios = new HashSet<Municipio>();
        }
    
        public int CodigoProvincia { get; set; }
        public string NombreProvincia { get; set; }
    
        public virtual ICollection<Municipio> Municipios { get; set; }
    }
}
