//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyect_P3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULO
    {
        public VEHICULO()
        {
            this.ARTICULOSFOTOS = new HashSet<ARTICULOSFOTO>();
        }
    
        public int IDVehiculo { get; set; }
        public int IDUsuario { get; set; }
        public int IdCategoria { get; set; }
        public int IdMarca { get; set; }
        public int IDTipo { get; set; }
        public int IdMotor { get; set; }
        public int CodigoMunicipio { get; set; }
        public string Modelo { get; set; }
        public int Año { get; set; }
        public string Color { get; set; }
        public string Placa { get; set; }
        public string NumeroChasis { get; set; }
        public Nullable<decimal> Kilometraje { get; set; }
        public decimal Precio { get; set; }
        public string Descripcion { get; set; }
        public string Condicion { get; set; }
        public bool Estatus { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public string Contacto { get; set; }
        public string Observaciones { get; set; }
        public bool Vendido { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public bool Destacado { get; set; }
        public int NumeroVistas { get; set; }
    
        public virtual ICollection<ARTICULOSFOTO> ARTICULOSFOTOS { get; set; }
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual MARCA MARCA { get; set; }
        public virtual MOTORE MOTORE { get; set; }
        public virtual Municipio Municipio { get; set; }
        public virtual TIPOS TIPOS { get; set; }
        public virtual USER USER { get; set; }
    }
}
